from django.shortcuts import render,HttpResponseRedirect
from .forms import  ClientStore, CompteGestion
from .models import  Client, Compte
from django.http import HttpResponse

#ClientRegistration,
#User,
# Create your views here.
#def add_show(request):
    #if request.method == 'POST':
       #fm = ClientRegistration(request.POST)
        #if fm.is_valid():
            #nm = fm.cleaned_data['name']
            #tl = fm.cleaned_data['telephone']
            #em = fm.cleaned_data['email']
            #pw = fm.cleaned_data['password']
            #reg = User(name = nm, telephone = tl, email = em, password = pw)
            #reg.save()
            #fm = ClientRegistration()
    #else:
        #fm = ClientRegistration()
    #return render(request, 'client/addandshow.html',{'form':fm})
#cette fonction permet d'ajouteret d'afficher les infos d'un client

def home(request):
        return render(request, 'home.html')
    
    
def connexion(request):
        return render(request, 'connexion.html')   


    
#def comptes_view(request):
 #   return HttpResponse('LES COMPTES')





def traiter_client(request):
    if request.method == 'POST':
        fm = ClientStore(request.POST)
        if fm.is_valid():
            nom = fm.cleaned_data['nom']
            pren = fm.cleaned_data['prenom']
            tel = fm.cleaned_data['telephone']
            adr = fm.cleaned_data['adresse']
            reg = Client(nom = nom, prenom = pren, telephone =tel , adresse = adr)
            reg.save()
            fm = ClientStore()
    else:
        fm = ClientStore()
    clien = Client.objects.all()
    return render(request, 'Clients/edit.html',{'form':fm, 'cli':clien})

#cette fonction permet de supprimer les donnes
def delete_data(request, id):
    if request.method == 'POST':
        pi = Client.objects.get(pk=id)
        pi.delete()
        return HttpResponseRedirect('/')
    

def traiter_compte(request):
    if request.method == 'POST':
        fm = CompteGestion(request.POST)
        if fm.is_valid():
            num = fm.cleaned_data['numero de compte']
            cli = fm.cleaned_data['client']
            solde = fm.cleaned_data['solde']
            jr = fm.cleaned_data['date ouverture']
            cpt = Compte(numero_de_compte = num, client = cli, solde =solde , date_ouverture = jr)
            cpt.save()
            fm = CompteGestion()
    else:
        fm = CompteGestion()
    compt = Compte.objects.all()
    return render(request, 'Comptes/edite.html',{'form':fm, 'cpt':compt})

#cette fonction permet de supprimer les donnes
def delete_data(request, id):
    if request.method == 'POST':
        pi = Compte.objects.get(pk=id)
        pi.delete()
        return HttpResponseRedirect('/')
    
    
# Generated by Django 4.1.2 on 2022-10-18 23:59

#from django.db import migrations, models


#class Migration(migrations.Migration):

 #   initial = True

  #  dependencies = [
   # ]

    #operations = [
     #   migrations.CreateModel(
      #      name='User',
       #     fields=[
        #        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
         #       ('name', models.CharField(max_length=70)),
          #      ('telephone', models.CharField(max_length=100)),
           #     ('email', models.CharField(max_length=100)),
            #    ('password', models.CharField(max_length=100)),
#            ],
 #       ),
  #  ]
 