# Generated by Django 4.1.2 on 2022-11-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_compte_client_alter_compte_jour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(max_length=70),
        ),
        migrations.AlterField(
            model_name='compte',
            name='numero',
            field=models.IntegerField(max_length=11, verbose_name='Numero'),
        ),
    ]
