# Generated by Django 4.1.3 on 2022-11-20 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0008_agence_region_role_remove_client_actif_client_lieu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='region',
            new_name='agence',
        ),
        migrations.AddField(
            model_name='operation',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.agence'),
        ),
        migrations.AddField(
            model_name='operation',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.role'),
        ),
        migrations.AddField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
