# Generated by Django 4.1.3 on 2022-11-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_rename_region_profil_agence_operation_agence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
