# Generated by Django 4.1.3 on 2022-11-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_client_agence_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='numero',
            field=models.CharField(max_length=100),
        ),
    ]
