# Generated by Django 4.1.3 on 2022-11-20 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_compte_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
    ]
