# Generated by Django 4.1.3 on 2022-11-20 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_compte_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.region'),
        ),
    ]
