# Generated by Django 4.1.3 on 2022-11-23 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_operation_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.role'),
        ),
    ]
